# Not -r because we modify this variable in the env specific vars file.
typeset -a DEFAULTS__XCODE_THEME_ACTIONS=(
	"mono"
)

# Not -r because we can modify this variable in the env specific vars file.
# Only useful when filter mode is whitelist.
typeset -a DEFAULTS__DARK_MODE_FOR_SAFARI_WHITELISTED_SITES=(
	"https://ipfs.io/ipfs/QmbpRxBZ5HDZDVRoeAU8xFYnoP4r5eGCxdkmfFW3JbA6mq/"
	"https://web.archive.org/web/20150908004746/https://developer.apple.com/library/mac/documentation/cocoa/conceptual/coredata/Articles/cdNSAttributes.html"
	"https://web.archive.org/web/20150922144626/https://developer.apple.com/library/mac/documentation/General/Conceptual/DevPedia-CocoaCore/KVO.html"
	"https://web.archive.org/web/20150922144639/https://developer.apple.com/library/mac/documentation/General/Conceptual/DevPedia-CocoaCore/KeyValueCoding.html"
	"https://www.itcodar.com/sql/sql-database-design-best-practice-addresses.html"
	"https://www.reddit.com/dev/api/oauth"
	
	"a.simplemdm.com"
	"academy.realm.io"
	"access.redhat.com"
	"admin.gandi.net"
	"admin.google.com"
	"airbnb.com"
	"akismet.com"
	"alexcharlton.co"
	"alexkutas.com"
	"allocine.fr"
	"alstudio.cz1.quickconnect.to"
	"amazon.fr"
	"ameli.fr"
	"andybargh.com"
	"andyibanez.com"
	"api.slack.com"
	"app.mailjet.com"
	"app.pagerduty.com"
	"app.pallet.com"
	"apple.github.io"
	"apple.stackexchange.com"
	"appleid.apple.com"
	"appsloveworld.com"
	"appstoreconnect.apple.com" # Thanks Apple for not supporting the Dark Mode you introduced…
	"ascii-code.com"
	"asciidoctor.org"
	"askubuntu.com"
	"auth0.com"
	"autoentrepreneur.urssaf.fr"
	"autoitscript.com"
	"baeldung.com"
	"bbs.archlinux.org"
	"betterprogramming.pub"
	"bigthink.com"
	"bionconsulting.com"
	"blog.6nok.org"
	"blog.canopas.com"
	"blog.cubieserver.de"
	"blog.gnoack.org"
	"blog.hobbyistsoftware.com"
	"blog.httpwatch.com"
	"blog.jooq.org"
	"blog.logrocket.com"
	"blog.ploeh.dk"
	"blog.rsisecurity.com"
	"blog.searce.com"
	"blog.waleedkhan.name"
	"blogs.microsoft.com"
	"brainyquote.com"
	"britishgeologicalsurvey.github.io"
	"bsonspec.org"
	"bugs.debian.org"
	"bugs.webkit.org"
	"build5nines.com"
	"business.paypal.com"
	"businessinsider.com"
	"cagankiraz.medium.com"
	"calendly.com"
	"calmcode.io"
	"carlosbecker.com"
	"cdimage.ubuntu.com"
	"cfspart.impots.gouv.fr"
	"chiark.greenend.org.uk"
	"cloud.google.com"
	"cloudflare.com"
	"cobeisfresh.com"
	"cocoacasts.com"
	"codeburst.io"
	"codeopinion.com"
	"community.cloudflare.com"
	"community.judo.app"
	"community.synology.com"
	"community.ui.com"
	"computerhistory.org"
	"console.cloud.google.com"
	"crockford.com"
	"crossover.com"
	"crossposter.masto.donte.com.br"
	"crt.sh"
	"css-tricks.com"
	"cuisine.journaldesfemmes.fr"
	"cyberciti.biz"
	"danielroelfs.com"
	"dash.teams.cloudflare.com"
	"dashboard.stripe.com"
	"database.guide"
	"datascience.stackexchange.com"
	"davemeehan.com"
	"dba.stackexchange.com"
	"dbadiaries.com"
	"dbohdan.com"
	"debian.org"
	"devbits.app"
	"developer.pagerduty.com"
	"developer.twitter.com"
	"developers.facebook.com"
	"devops.stackexchange.com"
	"devroom.io"
	"digitalocean.com"
	"discuss.hashicorp.com"
	"disk-decipher.app"
	"distro.ibiblio.org"
	"dmarcly.com"
	"docs.ansible.com"
	"docs.asciidoctor.org"
	"docs.cleverbridge.com"
	"docs.datomic.com"
	"docs.getutm.app"
	"docs.gitea.io"
	"docs.gitlab.com"
	"docs.k3s.io"
	"docs.opencv.org"
	"docs.oracle.com"
	"dsp.stackexchange.com"
	"easy-readers.ro"
	"eclecticlight.co"
	"econsulat.ro"
	"elastic.co"
	"elonmusk.today"
	"en.wikipedia.org"
	"en.wiktionary.org"
	"english.stackexchange.com"
	"epita-alumni.org"
	"epochconverter.com"
	"ericasadun.com"
	"esker.com"
	"eterna.com.au"
	"evian-tourisme.com"
	"explainextended.com"
	"fluxcd.io"
	"forum.affinity.serif.com"
	"forums.docker.com"
	"fr.babbel.com"
	"fr.wikipedia.org"
	"freedesktop.org"
	"fullstackml.com"
	"funet.fi"
	"furbo.org"
	"fusionauth.io"
	"galaxus.ch"
	"garysieling.com"
	"geekpeek.net"
	"girlsaskguys.com"
	"git-scm.com"
	"github.blog"
	"gitolite.com"
	"gitpay.me"
	"gksoft.com"
	"gnu.org"
	"goaskalice.columbia.edu"
	"golinuxcloud.com"
	"grabbyaliens.com"
	"graphql.org"
	"groups.google.com"
	"hackerfactor.com"
	"heckj.github.io"
	"help.sap.com"
	"howtogeek.com"
	"howtouselinux.com"
	"htmjs.dev"
	"httpwg.org"
	"hub.docker.com"
	"icann.org"
	"iknowwhatyoudownload.com"
	"ikyle.me"
	"imageoptim.com"
	"impots.gouv.fr"
	"infoq.com"
	"investopedia.com"
	"iosexample.com"
	"issuehunt.io"
	"iterm2.com"
	"itsolutionstuff.com"
	"jllnmercier.medium.com"
	"jobs.apple.com"
	"jobs.lever.co"
	"jwt.io"
	"kaggle.com"
	"kernel.org"
	"konradreiche.com"
	"kubernetes.io"
	"la-maison-bleue.fr"
	"lafibre.info"
	"learn.hashicorp.com"
	"learn.microsoft.com"
	"leboncoin.fr"
	"lickability.com"
	"lifehacker.com"
	"lingohub.com"
	"linkedin.com"
	"lists.w3.org"
	"lloydatkinson.net"
	"lmdb.tech"
	"loc.gov"
	"lucumr.pocoo.org"
	"macg.co"
	"mackungfu.org"
	"macports.org"
	"mail-archive.com"
	"maligned.transilien.com"
	"mamutuelle.mgen.fr"
	"man7.org"
	"marcosantadev.com"
	"marketplace.visualstudio.com"
	"martiancraft.com"
	"martinfowler.com"
	"mathstat.dal.ca"
	"matklad.github.io"
	"matteomanferdini.com"
	"medium.com"
	"metebalci.com"
	"mhash.sourceforge.net"
	"mon-compte.enedis.fr"
	"mongodb.com"
	"monip.org"
	"moovago.com"
	"mroi.github.io"
	"mxtoolbox.com"
	"my-json-server.typicode.com"
	"mynixos.com"
	"n-skvortsov-1997.github.io"
	"n8n.io"
	"nango.dev"
	"netspi.com"
	"news.ycombinator.com"
	"nginx.com"
	"nixos.org"
	"nixpacks.com"
	"nlpdemystified.org"
	"marchintosh.com"
	"matomo.org"
	"microsoft.com"
	"oauth.com"
	"oauth.net"
	"objc.io"
	"oilshell.org"
	"old.reddit.com"
	"oldlinux.org"
	"oleb.net"
	"one.dash.cloudflare.com"
	"openfolder.sh"
	"openid.net"
	"openldap.org"
	"openradar.appspot.com"
	"opensource.com"
	"openssl.org"
	"oreilly.com"
	"osintframework.com"
	"oss.issuehunt.io"
	"ottverse.com"
	"pagerduty.com"
	"parisaeroport.fr"
	"passkeys.directory"
	"passkeys.io"
	"paulbourke.net"
	"pbrown.me"
	"pdq.com"
	"people.skolelinux.org"
	"perfect.org"
	"piglei.com"
	"pioneli.com"
	"pkl-lang.org"
	"pointfree.co"
	"portal.azure.com"
	"postgis.net"
	"postgreshelp.com"
	"postgresonline.com"
	"postgresqltutorial.com"
	"powerdmarc.com"
	"predemande-permisdeconduire.ants.gouv.fr"
	"prestigere.gercop-extranet.com"
	"prieres-catholiques.net"
	"privatebin.info"
	"projecteuler.net"
	"proxie.app"
	"psql-tips.org"
	"pvdz.ee"
	"pyimagesearch.com"
	"pynative.com"
	"quickbirdstudios.com"
	"quillette.com"
	"quora.com"
	"qwerty.dev"
	"rapidapi.com"
	"raspberry-pi.developpez.com"
	"raspberrypi.stackexchange.com"
	"redis.io"
	"rerb-leblog.fr"
	"retrocomputing.stackexchange.com"
	"rfc.zeromq.org"
	"rfc-editor.org"
	"ruby-doc.org"
	"rutorrent.frostland.fr"
	"salesforce.stackexchange.com"
	"salon.com"
	"scriptingosx.com"
	"searx.be"
	"sebastiancarlos.medium.com"
	"security.stackexchange.com"
	"serverfault.com"
	"service-public.fr"
	"shafik.github.io"
	"showrss.info"
	"simpleromanian.com"
	"simplicityissota.substack.com"
	"social.msdn.microsoft.com"
	"social.technet.microsoft.com"
	"softwareengineering.stackexchange.com"
	"soundproofingguide.com"
	"specifications.freedesktop.org"
	"sqltutorial.org"
	"sslhow.com"
	"stripe.com"
	"sumologic.com"
	"superuser.com"
	"support.discord.com"
	"swiftleejobs.com"
	"swiftpackageregistry.com"
	"swiftui-lab.com"
	"systranbox.com"
	"szopa.medium.com"
	"tableflipapp.com"
	"talent.io"
	"tapas.io"
	"tech.olx.com"
	"techyourchance.com"
	"tecmint.com"
	"text.npr.org"
	"the-art-of-web.com"
	"thediscoblog.com"
	"thegeekstuff.com"
	"theguardian.com"
	"thehackernews.com"
	"themathdoctors.org"
	"theonion.com"
	"thinking.ajdecon.org"
	"thomasbandt.com"
	"thread.house"
	"timestamp-converter.com"
	"tinycorelinux.net"
	"toml.io"
	"tukaani.org"
	"unicode.org"
	"unix.stackexchange.com"
	"usebruno.com"
	"usernamegenerator.com"
	"v6.testmyipv6.com"
	"vadimbulavin.com"
	"vadimkravcenko.com"
	"validator.w3.org"
	"vaultproject.io"
	"vectordb.com"
	"vertabelo.com"
	"video.stackexchange.com"
	"vigneshwarar.substack.com"
	"vimeo.zendesk.com"
	"vin01.github.io"
	"vlang.io"
	"volt-app.com"
	"vorpus.org"
	"voscomptesenligne.labanquepostale.fr"
	"vsanthanam.com"
	"vultr.com"
	"w3.org"
	"w3schools.com"
	"webmasters.stackexchange.com"
	"wiki.archlinux.org"
	"wiki.csnu.org"
	"wiki.debian.org"
	"wiki.tinycorelinux.net"
	"www3.yggtorrent.wtf"
	"x0r.fr"
	"xdgbasedirectoryspecification.com"
	"xkcd.com"
	"yaml.org"
	"yaml-multiline.info"
	"yolken.net"
	"youperv.com"
	"zewo.io"
	"zompist.com"
	"zufallsheld.de"
)
# Not -r because we can modify this variable in the env specific vars file.
# Only useful when filter mode is blacklist.
typeset -a DEFAULTS__DARK_MODE_FOR_SAFARI_BLACKLISTED_SITES=(
	"172.16.0.1"
	"localhost"
	
	"9gag.com"
	"aaronbos.dev" # Already dark
	"about.me"
	"accounts.panic.com"
	"anasinorbi.ro"
	"anatolyzenkov.com" # Already dynamic, but not detected as such
	"andrewlock.net" # Already dark; does not work
	"anti-captcha.com"
	"app.amplitude.com" # Already dynamic, but not detected as such
	"app.n26.com"
	"app.slack.com" # Already dynamic, but not detected as such
	"appartager.com"
	"apple.com"
	"ashgw.me" # Already dark
	"ashishb.net" # Already dark; does not work
	"assure.ameli.fr"
	"auth.eversports.com"
	"authors.apple.com"
	"autodiscover.mail.frostland.fr"
	"avanderlee.com" # Already dynamic, but not detected as such
	"batou.dev"
	"beta.music.apple.com"
	"beta.you.com"
	"bienvenueaumontsaintmichel.com"
	"bienvenueaumontsaintmichel.fr"
	"billetreduc.com" # Already dynamic, but not detected as such
	"blog.kagi.com" # Already dynamic, but not detected as such
	"blog.trl.sn"
	"brew.sh"
	"browser.kagi.com"
	"browserbench.org"
	"bsky.app" # Already dynamic, but not detected as such
	"business.apple.com" # Does not work
	"camanis.net"
	"canva.com"
	"cinemaspathegaumont.com"
	"clipbook.app" # Already dark
	"cnpnet.cnp.fr"
	"cocacola.fr"
	"coinbase.com" # Already dynamic, but not detected as such
	"connexion.numericable.fr"
	"crablang.org" # Already dark
	"css-tricks.com"
	"cuntempire.com" # Does not work
	"daringfireball.net"
	"dash.cloudflare.com"
	"dashboard.nativeconnect.app"
	"dashboard.twitch.tv" # Already dark
	"datatracker.ietf.org" # Already dynamic, but not detected as such
	"denudeart.com" # Does not work
	"departmentmap.store"
	"developer.apple.com"
	"developers.cloudflare.com"
	"deviantart.com"
	"dgerrells.com" # Already dark; does not work
	"discord.com"
	"discordapp.com"
	"disneyplus.com"
	"docs.brew.sh"
	"docs.docker.com"
	"docs.github.com" # Already dynamic, but not detected as such
	"docs.k3s.io" # Already dynamic, but not detected as such
	"docs.python.org" # Already dynamic, but not detected as such
	"docs.swift.org" # Already dynamic, but not detected as such
	"draves.org"
	"duckduckgo.com"
	"dudzik.co" # Already dark; does not work
	"duriansoftware.com"
	"dz4k.com" # Already dark; does not work
	"eisfunke.com" # Already dark
	"electricsheep.org"
	"eporner.com" # Already dark
	"espace-assure.gmf.fr"
	"espace-republique.fr"
	"etherscan.io" # Already dynamic, but not detected as such
	"eversports.fr"
	"everytimezone.com"
	"facebook.com"
	"facegram.co.za" # Does not work
	"fanvue.com" # Already dynamic, but not detected as such
	"faphouse.com" # Already dynamic (when forced to), but not detected as such
	"fastvideoindexer.com"
	"fatbobman.com" # Already dynamic, but not detected as such
	"feathericons.com"
	"fikfap.com" # Already dark
	"fluence.network" # Already dark
	"fly.io"
	"foon.uk" # Already dynamic, but not detected as such
	"formulae.brew.sh"
	"forums.macrumors.com"
	"forums.swift.org"
	"fuckingswiftui.com"
	"fusionauth.io" # Already dynamic, but not detected as such
	"furyroom.fr"
	"geoff.greer.fm" # Already dynamic, but not detected as such
	"gist.github.com"
	"github.com"
	"gitlab.com"
	"gleam.run" # Does not work
	"gmf.fr"
	"happn.com"
	"help.kagi.com" # Already dark
	"help.steampowered.com"
	"hi-way.io"
	"hiandrewquinn.github.io" # Already dynamic, but not detected as such
	"home.vollink.com"
	"homepages.cwi.nl"
	"honeypot.net" # Already dynamic, but not detected as such
	"hotels.le-mont-saint-michel.com"
	"hurl.wtf" # Does not work (and already dark)
	"hypermedia.systems" # Already dynamic, but not detected as such
	"icloud.com"
	"icloud.developer.apple.com"
	"ikea.com"
	"ilmarilauhakangas.fi"
	"imdb.com"
	"inessential.com" # Already dynamic, but not detected as such
	"informatiiconsulare.ro"
	"inspect.new" # Already dark; does not work
	"interieur.gouv.fr" # Already dynamic, but not detected as such
	"jegeremacartenavigo.fr"
	"k0sproject.io" # Already dark; does not work
	"kagi.com"
	"kennethnym.com" # Already dynamic, but not detected as such
	"kibty.town" # Already dark; does not work
	"kimcartoon.li" # Already dark
	"lapcatsoftware.com"
	"le-mont-saint-michel.com"
	"learn.microsoft.com" # Does not work
	"leetcode.com"
	"lg.com"
	"lidentitenumerique.laposte.fr"
	"linear.app"
	"linuxize.com" # Already dynamic, but not detected as such
	"loneliness.one"
	"louvre.fr"
	"maciejwalkowiak.com" # Already dynamic, but not detected as such
	"macintoshgarden.org"
	"macintoshrepository.org"
	"macos9lives.com"
	"madamevoyeur.com"
	"mariahealthandbeauty.mynuskin.com"
	"meatfighter.com" # Already dark
	"mega.nz" # Already dynamic, but not detected as such
	"milovana.com" # Already dark
	"mindbodyonline.com"
	"minus-ze.ro" # Already dynamic, but not detected as such
	"mobile.twitter.com"
	"moncompte.numericable.fr"
	"moncompte.sncf.com"
	"mondossiernotaire.fr"
	"mozilla.github.io" # Already dark
	"msha.ke"
	"mxb.dev" # Already dynamic, but not detected as such
	"my.ionos.fr"
	"nativeconnect.app"
	"netnewswire.com"
	"nextcomputers.org"
	"nextstep33.info"
	"nightwater.email" # Already dark; does not work
	"nitric.io" # Already dark
	"noob-tv.com"
	"nopeforge.org" # Already dark
	"notes.ghed.in" # Already dynamic, but not detected as such
	"notion.so" # Already dynamic, but not detected as such
	"nsdateformatter.com"
	"nshipster.com" # Already dynamic, but not detected as such
	"nuskin.com"
	"ohanaware.com"
	"opensource.apple.com" # Already dynamic, but not detected as such
	"oui.sncf"
	"ounapuu.ee" # Already dark
	"oxyd.games"
	"packaging.python.org"
	"pangeasoft.net" # Already dark
	"parametric.press"
	"pavillonwagram.com"
	"paypal.com"
	"peps.python.org" # Already dynamic, but not detected as such
	"pizzahut.fr"
	"plateforme-covid-idf.aphp.fr"
	"plausible.io" # Already dynamic, but not detected as such
	"pointerpointer.com"
	"polpiella.dev" # Already dynamic, but not detected as such
	"porn-blog.xyz" # Already dark
	"postgresql.org"
	"powerlanguage.co.uk"
	"prepacode-enpc.fr"
	"primevideo.com"
	"quic.video" # Already dark
	"quora.com" # Does not work
	"receive-sms.com"
	"reddit.com"
	"redditp.com"
	"responsivepx.com"
	"rlimit.com"
	"sailorhg.com"
	"saint-eugene.net" # Does not work
	"samueloph.dev" # Already dark
	"sashalakhman.com"
	"scrolldit.com"
	"secure.digiposte.fr"
	"selfservicerepair.com"
	"sha256algorithm.com"
	"sixcolors.com" # Already dynamic, but not detected as such
	"sketch.com"
	"sncf.com"
	"soap2day.ac"
	"soundcloud.com"
	"soundhound.com"
	"stackoverflow.com"
	"steamcommunity.com"
	"stocknear.com" # Does not work
	"store.serif.com"
	"store.steampowered.com"
	"studio.blender.org" # Does not work
	"support.apple.com"
	"swift.org"
	"swiftonserver.com" # Already dynamic, but not detected as such
	"swiftpackageindex.com"
	"taimapp.io" # Already dark; does not work
	"taquin.net"
	"test.hozana.org"
	"theotokos.fr"
	"thetvdb.com"
	"thewatchcartoononline.tv"
	"ticketlouvre.fr"
	"tinyapps.org" # Already dynamic, but not detected as such
	"togever.co"
	"torrentleech.org"
	"tour.gleam.run" # Already dark
	"trace.yshui.dev" # Already dark
	"try.constructor.dev"
	"tumblr.com"
	"tv.apple.com"
	"tvtime.com"
	"twitch.tv" # Already dark
	"twitter.com"
	"userinyerface.com"
	"useyourloaf.com"
	"vapor.codes"
	"vimeo.com"
	"voscomptesenligne.labanquepostale.fr"
	"wannonce.com"
	"watchcartoononline.com"
	"web.archive.org"
	"webmail.imm.fr"
	"webmail.numericable.fr"
	"wiki.torrentleech.org"
	"wildblue.digital"
	"winonx.com"
	"woob.tech"
	"ww3.yggtorrent.gg"
	"www.apple.com"
	"www.icloud.com"
	"www.tvtime.com"
	"www2.impots.gouv.fr"
	"www2.yggtorrent.ch"
	"www2.yggtorrent.gg"
	"www3.yggtorrent.nz"
	"www3.yggtorrent.pe"
	"www5.yggtorrent.la"
	"x.com" # Already dynamic, but not detected as such
	"xeiaso.net" # Already dynamic, but not detected as such
	"xstumbl.com" # Does not work
	"yespark.fr"
	"yggtorrent.ch"
	"yggtorrent.gg"
	"yggtorrent.la"
	"you.com"
	"zazzle.com"
	"zazzle.fr"
	"zx2c4.com" # Already dark; does not work
)


# Sourcing env specific vars file.
test -f "./vars/$COMPUTER_GROUP.zsh" && source "./vars/$COMPUTER_GROUP.zsh" || true
