= Frizlab’s Conf
François Lamboley <fload@me.com>

Originally based on https://github.com/wincent/wincent[wincent’s conf], I then
realized Ansible was too complex and had too many dependencies to continue using
it for managing dotfiles and some defaults. (Funnily enough, wincent seems to
have reached the same conclusion as me and switched away from Ansible in his
conf repo too!)

The repo is now pure zsh. You can try and install it at home using `./install`.
When prompted for the passphrase, just leave it empty; the actions requiring the
password will simply fail. On macOS, the command-line tools are enough to use
this repo; on Linux you should install `ccrypt`, `curl`, `git`, `locale-gen` and
`m4`.

⚠️ Use at your own risks! This repo installs defaults I’m confortable with, but
is in no way intended to be used by anybody else than me.

To simply see what I do, and steal whatever you like, go in the `src/components`
folder. There is one folder per component I install.

== My `brew` Setup
I do a somehow twisted Homebrew setup, with a “system” brew and a “user” one.
Additionally, on an M1 Mac, for both these brews, there will be an “x86” and an
“arm64” install done.

This is done to be able to use brew on a multi-user machine properly: the admin
manages the system brew, and “normal” users can use a “user” brew without
issues (well, at least for formulae which do not fail compilation, but that’s
another problem).

_Future direction_: Fully switch to Nix, which manages a multi-user install
properly, and is IMHO generally better, though more complex.

== Notes/TODOs

=== `brew` installation in `/usr/local`
Mostly from https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh,
but simplified.
[source,bash]
----
cd /usr/local
directories=(bin etc include lib sbin share var opt
             share/zsh share/zsh/site-functions
             var/homebrew var/homebrew/linked
             Cellar Caskroom Homebrew Frameworks)
for d in $directories; do sudo mkdir "$d"; done
for d in $directories; do sudo chown -h frizlab:staff "$d"; done
curl -SL https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C /usr/local/Homebrew
ln -sf /usr/local/Homebrew/bin/brew /usr/local/bin/brew
/usr/local/bin/brew update --force
----

=== A Thing from Twitter

https://twitter.com/ryleyherrington/status/1354546825739472897

== Some doc related to `.bash_profile`, `.bashrc` & others

=== Random links
- man bash, § INVOCATION
- https://unix.stackexchange.com/a/119675
- https://superuser.com/a/789705
- https://kb.iu.edu/d/abdy
- https://github.com/rbenv/rbenv/wiki/unix-shell-initialization

=== Roles

_Lexicographic note_: When I say “conf that is propagated to its children,” I mean
for instance `export var=`, or `export -f function_name` in bash. That is everything
that is exported to children of the shell.

==== `.bash_profile`
Should contain only bash-specific conf that is propagated to its children.
For instance, exported env variables, exported functions (this is possible with
bash with `export -f func_name`).

It is important to know aliases cannot be exported.

==== `.profile`
Should contain only POSIX-compliant conf that is propagated to its children.

*Important*: In theory https://stackoverflow.com/a/29239838[it is not possible to
export a function in a POSIX shell], though `bash --posix` does not
complain when doing it, for whatever reason, neither on Debian, nor on macOS!

==== `.bashrc`
Should contain only bash-specific conf that cannot be propagated to children.
Aliases might fall into this category, but you might want to put them in `.shrc`
if they’re POSIX-compliant.

==== `.shrc`
(Not a standard file per-se.) +
Should contain only POSIX-compliant conf that cannot be propagated to children
(e.g. aliases).


=== Scenarios
All login shells are considered interactive. +
All of this has been tested on macOS and Debian. On both, the shell is `bash`,
even when launching an `sh` shell. However, when `bash` is launched as `sh`, it
tries and mimic the startup behavior of `sh`, while still conforming to the
POSIX standard (says the man of bash).

==== bash, login
* `.bash_profile`
** imports `.profile`
** …
** imports `.bashrc`
*** imports `.shrc`
*** …

==== bash, non-login, interactive
* `.bashrc`
** imports `.shrc`
** …

==== sh, login
* `.profile`
** …
** imports `.shrc` via the `ENV` variable, only if it is not already set

==== sh, non-login, interactive
* `.shrc` via the `ENV` variable, only if the login shell above had set it

==== bash --posix
Does not load anything unless the `ENV` var is set, in which case it loads the
file in `$ENV` (in theory; not the behavior observed on macOS; untested on
Debian).
