---
# Provide an extension point for .bash_profile
- name: "make ~/.bash_profile.d"
  file: path="{{ ansible_env.HOME }}/.bash_profile.d" state=directory mode=0700

- include_vars: links.yml
- import_tasks: "{{ lib_folder }}/links.yml"

- name: "create templates"
  template: src="{{ item | regex_replace('^\.', '_.') | regex_replace('/\.', '/_.') }}.jinja"
            dest="{{ ansible_env.HOME }}/{{ item }}"
            mode="{{ '0700' if item.endswith('.sh') else '0600' }}"
  loop: "{{ dotfile_templates }}"

# vim: ts=2 sw=2 et
