---
# Provide an extension point for some dot-files
- name: "make dotfiles folders"
  file: path="{{ ansible_env.HOME }}/{{ item }}" state=directory mode=0700
  loop: "{{ dotfile_folders }}"

- import_tasks: "{{ _lib_folder }}/links.yml"
  vars:
    lnk__backup_dir: "{{ backup_dir }}"
    lnk__backup_dir_mode: "{{ backup_dir_mode }}"
    lnk__dest_dir: "{{ ansible_env.HOME }}"
    lnk__link_mode: "0600"
    # Contains an array of tuples (link_base_name, link_target_base_name)
    lnk__files: "{{
      dotfile_files |
      zip(
        dotfile_files |
        map('regex_replace', '^\\.', '_.') |
        map('regex_replace', '/\\.', '/_.')
      ) |
      list
    }}"

- name: "create templates"
  template: src="{{ item | regex_replace('^\.', '_.') | regex_replace('/\.', '/_.') }}.jinja"
            dest="{{ ansible_env.HOME }}/{{ item }}"
            mode="{{ '0700' if item.endswith('.sh') else '0600' }}"
  loop: "{{ dotfile_templates }}"

# vim: ts=2 sw=2 et
