# Dockerfile
# vim: ts=3 sw=3 noet

# Must be a Dockerfile.base image
ARG BASE_IMAGE

FROM ${BASE_IMAGE}
LABEL maintainer="François Lamboley <fload@me.com>"
# Wanted to use ${BASE_IMAGE} but it does not work…
LABEL description="A base image to install Frizlab’s conf as a standard user."


RUN useradd normaluser && mkdir "/home/normaluser" && chown normaluser:users "/home/normaluser"
USER normaluser:users

WORKDIR /home/normaluser
