---
lnk__backup_dir: "{{ third_party_bin_backup_dir }}"
lnk__backup_dir_mode: "{{ backup_dir_mode }}"
lnk__dest_dir: "{{ third_party_bin_dir }}"
lnk__link_mode: "0644"
# Only used to compute lnk__files
filtered_packages: "{{ packages | rejectattr('author', 'equalto', ansible_user_id) | list }}"
filtered_flattened_paths: "{{ filtered_packages | sum(attribute='bin_paths', start=[]) }}"
# Contains an array of tuples (link_base_name, link_target_base_name)
# Base name here is name of the bin, without extension
lnk__files: "{{
  (
    filtered_flattened_paths | map('regex_replace', '(\\.[^.]*)?$', '') | map('regex_replace', '^.*/([^/]*)$', '\\1') |
    zip(filtered_flattened_paths) |
    list
  ) + (
    links | map(attribute='name') |
    zip(links | map(attribute='dest')) |
    list
  )
}}"

# vim: ts=2 sw=2 et
