---
lnk__backup_dir: "{{ backup_dir }}"
lnk__backup_dir_mode: "{{ backup_dir_mode }}"
lnk__dest_dir: "{{ user_bin_dir }}"
lnk__link_mode: "0644"
# Contains an array of tuples (link_base_name, link_target_base_name)
# Base name here is name of the bin, without extension
lnk__files: "{{
  (
    bins | map('regex_replace', '(\\.[^.]*)?$', '') | map('regex_replace', '^.*/([^/]*)$', '\\1') |
    zip(bins) |
    list
  ) + (
    links | map(attribute='name') |
    zip(links | map(attribute='dest')) |
    list
  )
}}"

# vim: ts=2 sw=2 et
