---
bins:
  - local_brew_install.sh
  - set_sound_volume.sh

links:
# When compopt is not available (e.g. w/ Bash 3), at least we won’t get an error…
  - name: compopt
    dest: /usr/bin/true

# vim: ts=2 sw=2 et
