---
# TODO: Filter on compat
first_party_packages: "{{ packages | selectattr('author', 'equalto', ansible_user_id) | list }}"
third_party_packages: "{{ packages | rejectattr('author', 'equalto', ansible_user_id) | list }}"

# vim: ts=2 sw=2 et
