---
lnk__backup_dir: "{{ backup_3rdparty_bin_dir }}"
lnk__backup_dir_mode: "{{ backup_dir_mode }}"
lnk__dest_dir: "{{ third_party_bin_dir }}"
lnk__link_mode: "0644"
# Only used to compute lnk__files
filtered_bins: "{{ bins | rejectattr('author', 'equalto', ansible_user_id) | list }}"
# Contains an array of tuples (link_base_name, link_target_base_name)
# Base name here is name of the bin, without extension
lnk__files: "{{
  (
    filtered_bins | map(attribute='path') | map('regex_replace', '(\\.[^.]*)?$', '') | map('regex_replace', '^.*/([^/]*)$', '\\1') |
    zip(filtered_bins | map(attribute='path')) |
    list
  ) + (
    links | map(attribute='name') |
    zip(links | map(attribute='dest')) |
    list
  )
}}"

# vim: ts=2 sw=2 et
