source "./lib/xcode-theme.zsh"

source "./vars/ main.zsh"

source "./tasks/set-system-defaults.zsh"
source "./tasks/set-mail-defaults.zsh"
source "./tasks/set-safari-defaults.zsh"
source "./tasks/set-textedit-defaults.zsh"
source "./tasks/set-xcode-defaults.zsh"
source "./tasks/set-finder-defaults.zsh"
source "./tasks/set-alttab-defaults.zsh"
source "./tasks/set-activitymonitor-defaults.zsh"
source "./tasks/set-nova-defaults.zsh"
source "./tasks/set-preview-defaults.zsh"
source "./tasks/set-pixie-defaults.zsh"
source "./tasks/set-music-defaults.zsh"
source "./tasks/set-darkmodeforsafari-defaults.zsh"
