---
- name: "make user’s bin folder"
  file: path="{{ first_party_bin_dir }}" state=directory mode=0755
- name: "make user’s share folder"
  file: path="{{ first_party_share_dir }}" state=directory mode=0755

- name: "make 3rd party bin folder"
  file: path="{{ third_party_bin_dir }}" state=directory mode=0755
- name: "make 3rd party share folder"
  file: path="{{ third_party_share_dir }}" state=directory mode=0755

# Add some helper variables that derive from main
- include_vars: "derived.yml"

# Install 1st party binaries
- import_tasks: "pkg_links_bins.yml"
  vars:
    install_dest: "{{ first_party_bin_dir }}"
    packages_to_install: "{{ first_party_packages }}"
# Install 1st party share files
- import_tasks: "pkg_links_docs.yml"
  vars:
    packages_to_install: "{{ first_party_packages }}"
    base_dest: "{{ first_party_share_dir }}"

# Install 3rd party binaries
- import_tasks: "pkg_links_bins.yml"
  vars:
    install_dest: "{{ third_party_bin_dir }}"
    packages_to_install: "{{ third_party_packages }}"
# Install 3rd party share files
- import_tasks: "pkg_links_docs.yml"
  vars:
    packages_to_install: "{{ third_party_packages }}"
    base_dest: "{{ third_party_share_dir }}"

# Install links
- import_tasks: "{{ _lib_folder }}/links.yml"
  vars:
    lnk__link_mode: "0755"
    lnk__dest_dir: "{{ third_party_bin_dir }}"
    lnk__backup_dir: "{{ third_party_bin_dir }}/{{ backup_dir_basename }}"
    lnk__backup_dir_mode: "{{ backup_dir_mode }}"
    lnk__files: "{{
      (
        bin_links | map(attribute='name') |
        zip(bin_links | map(attribute='dest')) |
        list
      )
    }}"

# vim: ts=2 sw=2 et
