---
- name: "make user’s bin folder"
  file: path="{{ first_party_bin_dir }}" state=directory mode=0755
- name: "make user’s share folder"
  file: path="{{ first_party_share_dir }}" state=directory mode=0755

- name: "make 3rd party bin folder"
  file: path="{{ third_party_bin_dir }}" state=directory mode=0755
- name: "make 3rd party share folder"
  file: path="{{ third_party_share_dir }}" state=directory mode=0755

# Add some helper variables that derive from main
- include_vars: "derived.yml"

# Install 1st party binaries
- import_tasks: "pkg_links_one_folder.yml"
  vars:
    # Mode is totally useless as it will be applied to the links…
    mode: "0755"
    dest: "{{ first_party_bin_dir }}"
    extension_regex: "{{ file_extension_regex }}"
    paths: "{{ first_party_packages | sum(attribute='bin_paths', start=[]) }}"
# Install 1st party share files
- include_tasks: "pkg_links_one_folder.yml"
  vars:
    # Mode is totally useless as it will be applied to the links…
    mode: "0644"
    extension_regex: ""
    dest: "{{ first_party_share_dir }}/{{ cur_dest }}"
    paths: "{{ first_party_packages | sum(attribute='share_paths', start=[]) | selectattr('dest_folder', 'equalto', cur_dest) | sum(attribute='files', start=[]) }}"
  loop: "{{ first_party_packages | sum(attribute='share_paths', start=[]) | map(attribute='dest_folder') | list }}"
  loop_control:
    loop_var: "cur_dest"

# Install 3rd party binaries
- import_tasks: "pkg_links_one_folder.yml"
  vars:
    # Mode is totally useless as it will be applied to the links…
    mode: "0755"
    dest: "{{ third_party_bin_dir }}"
    extension_regex: "{{ file_extension_regex }}"
    paths: "{{ third_party_packages | sum(attribute='bin_paths', start=[]) }}"
# Install 3rd party share files
- include_tasks: "pkg_links_one_folder.yml"
  vars:
    # Mode is totally useless as it will be applied to the links…
    mode: "0644"
    extension_regex: ""
    dest: "{{ third_party_share_dir }}/{{ cur_dest }}"
    paths: "{{ third_party_packages | sum(attribute='share_paths', start=[]) | selectattr('dest_folder', 'equalto', cur_dest) | sum(attribute='files', start=[]) }}"
  loop: "{{ third_party_packages | sum(attribute='share_paths', start=[]) | map(attribute='dest_folder') | list }}"
  loop_control:
    loop_var: "cur_dest"

# Install links
- import_tasks: "{{ _lib_folder }}/links.yml"
  vars:
    lnk__link_mode: "0755"
    lnk__dest_dir: "{{ third_party_bin_dir }}"
    lnk__backup_dir: "{{ third_party_bin_dir }}/{{ backup_dir_basename }}"
    lnk__backup_dir_mode: "{{ backup_dir_mode }}"
    lnk__files: "{{
      (
        bin_links | map(attribute='name') |
        zip(bin_links | map(attribute='dest')) |
        list
      )
    }}"

# vim: ts=2 sw=2 et
