# Dockerfile
# vim: ts=3 sw=3 noet

ARG BASE_IMAGE=debian

FROM ${BASE_IMAGE}
LABEL maintainer="François Lamboley <fload@me.com>"
# Wanted to use ${BASE_IMAGE} but it does not work…
LABEL description="A base image to install Frizlab’s conf."


# Note: openssl is a dependency of ca-certificates and could be removed from the list
# Note: python (2) is needed only to activate the Python3 virtualenv (AFAICT)
# Note: gcc is for some pip installs. And it MUST be gcc, not clang *facepalm*
# Note: python3-dev is for some pip installs (obviously)
RUN apt-get update && apt-get install -y --no-install-recommends \
	ca-certificates \
	gcc \
	git \
	openssl \
	python \
	python3 \
	python3-dev \
&& rm -rf /var/lib/apt/lists/*

# TODO: I don’t really like having this here
COPY test-frizlabs-conf.sh /usr/local/bin/test-frizlabs-conf.sh
